title: "Usable Fonts"
description: >-
  Description ...

lang: en

author: menozero

# url: "https://menozero.github.io"
# baseurl: "/usable-fonts"

repository: menozero/usable-fonts
github_username: menozero

# theme: minima
# remote_theme: jekyll/minima
plugins:
  - "jekyll-github-metadata"
# - jekyll-remote-theme

liquid:
  error_mode: warn
  # strict_variables: true
  strict_filters: true
